### ISSUE TITLE
模版使用的os-name包不允许require语法，但是umi好像是用的require导入的

### ISSUE THREAD

**Issue by jxzzzhu** [arvinxx/umi-electron-template#627]
重现步骤：下载模板到本地，安装依赖后，`yarn start` 直接报错。

node版本：`v14.18.1`

报错日志：

```shell
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/lihuajie/Desktop/yxm/node_modules/os-name/index.js
  require() of ES modules is not supported.
  require() of /Users/lihuajie/Desktop/yxm/node_modules/os-name/index.js from /Users/lihuajie/Desktop/yxm/src/renderer/.umi/electron/main.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
  Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/lihuajie/Desktop/yxm/node_modules/os-name/package.json.
  
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1169:13)
      at Module.load (internal/modules/cjs/loader.js:992:32)
      at Module._load (internal/modules/cjs/loader.js:885:14)
      at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
      at Module.require (internal/modules/cjs/loader.js:1032:19)
      at require (internal/modules/cjs/helpers.js:72:18)
      at Object.os-name (/Users/lihuajie/Desktop/yxm/src/renderer/.umi/electron/main.js:31785:18)
      at __webpack_require__ (/Users/lihuajie/Desktop/yxm/src/renderer/.umi/electron/main.js:21:30)
      at Object../core/Logger/index.ts (/Users/lihuajie/Desktop/yxm/src/renderer/.umi/electron/main.js:31219:48)
      at __webpack_require__ (/Users/lihuajie/Desktop/yxm/src/renderer/.umi/electron/main.js:21:30)
```

**Comment by imfycc** [comment]
use os-name v4
